name: PR Commenter

on:
  pull_request:
    types: [opened]

jobs:
  add-comment:
    runs-on: ubuntu-latest

    steps:
      - name: Add Comment to Pull Request
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Thank you for opening this pull request!  
            Our team will review it shortly. 😊
